### ISSUE TITLE
not working...follow instructions and get same issue

### ISSUE THREAD

**Issue by itpick** [akhepcat/bridgeap#3]
I followed the wiki commands given:
sudo su -  
# cd /usr/local/src  
# git clone https://github.com/akhepcat/bridgeap.git  
# mkdir /etc/bridgeap  
# cp bridgeap/*conf* /etc/bridgeap  
# ln -s /usr/local/src/bridgeap/bridgeap /usr/local/sbin/  
# ln -s /usr/local/src/bridgeap /etc/init.d/  
# update-rc.d bridgeap defaults 

root@raspberrypi:/usr/local/src# sudo /usr/local/sbin/bridgeap start
Starting bridgeap interface bridging
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan0 ; Invalid argument.
failed to set Master mode

ps- i've spent probably way way too long trying to get a vpn client connection serving to the wifi from eth0 from my raspberry pi 3b+.  I was hoping this would actually going to solve my issues and end the hunt.

**Comment by akhepcat** [comment]
in the conf file, you'll find this:

IGNORE_MODE=0           # 1 if you want to ignore iwconfig mode set errors

set it to 1.

**Comment by itpick** [comment]
pi@raspberrypi:~ $ sudo /usr/local/sbin/bridgeap start
Starting bridgeap interface bridging
Configuration file: /usr/local/src/bridgeap/hostapd.conf-bridgeap
Failed to create interface mon.wlan0: -95 (Operation not supported)
wlan0: interface state UNINITIALIZED->COUNTRY_UPDATE
Internet Systems Consortium DHCP Server 4.3.5
Copyright 2004-2016 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
no such user: dhcpd

If you think you have received this message due to a bug rather
than a configuration issue please read the section on submitting
bugs on either our web page at www.isc.org or in the README file
before submitting a bug.  These pages explain the proper
process and the information we find helpful for debugging..

exiting.
dhcp server failed to start




I have stretch lite installed.  Btw, you have not specified the installation requirements in your readme.

**Comment by akhepcat** [comment]
wlan0: interface state UNINITIALIZED->COUNTRY_UPDATE

This means you haven't configured your wifi adapter correctly,
and you can do that using raspi-config

there's additional settings in the config file, which it looks like you need to change, in order to define the correct user for dhcp.

These are site-specific, basic system-administration issues, and not a problem with the script, which is why i'm closing the issue.
